language: ruby
os:
  - linux
services:
  - postgresql
  - mysql
script:
  - bundle exec rake first_run spec
jobs:
#  allow_failures: <-- factory-girl gem missing
#   - rvm: 2.3.1
#     gemfile: gemfiles/branch_v23-v26.gemfile
#     env: SOLIDUS_BRANCH=v2.3 DB=mysql
#   - rvm: 2.3.1
#     gemfile: gemfiles/branch_v23-v26.gemfile
#     env: SOLIDUS_BRANCH=v2.3 DB=postgresql
#   - rvm: 2.3.1
#     gemfile: gemfiles/branch_v23-v26.gemfile
#     env: SOLIDUS_BRANCH=v2.4 DB=mysql
#   - rvm: 2.3.1
#     gemfile: gemfiles/branch_v23-v26.gemfile
#     env: SOLIDUS_BRANCH=v2.4 DB=postgresql
  include:
  - rvm: 2.3.1
    gemfile: gemfiles/branch_v23-v26.gemfile
    env: SOLIDUS_BRANCH=v2.5 DB=mysql
  - rvm: 2.3.1
    gemfile: gemfiles/branch_v23-v26.gemfile
    env: SOLIDUS_BRANCH=v2.5 DB=postgresql
  - rvm: 2.3.1
    gemfile: gemfiles/branch_v23-v26.gemfile
    env: SOLIDUS_BRANCH=v2.6 DB=mysql
  - rvm: 2.3.1
    gemfile: gemfiles/branch_v23-v26.gemfile
    env: SOLIDUS_BRANCH=v2.6 DB=postgresql
  - rvm: 2.3.1
    gemfile: gemfiles/branch_v27-v29.gemfile
    env: SOLIDUS_BRANCH=v2.7 DB=mysql
  - rvm: 2.3.1
    gemfile: gemfiles/branch_v27-v29.gemfile
    env: SOLIDUS_BRANCH=v2.7 DB=postgresql
  - rvm: 2.3.1
    gemfile: gemfiles/branch_v27-v29.gemfile
    env: SOLIDUS_BRANCH=v2.8 DB=mysql
  - rvm: 2.3.1
    gemfile: gemfiles/branch_v27-v29.gemfile
    env: SOLIDUS_BRANCH=v2.8 DB=postgresql
  - rvm: 2.3.1
    gemfile: gemfiles/branch_v27-v29.gemfile
    env: SOLIDUS_BRANCH=v2.9 DB=mysql
  - rvm: 2.3.1
    gemfile: gemfiles/branch_v27-v29.gemfile
    env: SOLIDUS_BRANCH=v2.9 DB=postgresql
  - rvm: 2.4.0
    gemfile: Gemfile
    env: DB=mysql
  - rvm: 2.4.0
    gemfile: Gemfile
    env: DB=postgresql
